- name: "Add nodejs apt key"
  become: true
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: "Add nodejs 13.x ppa for apt repo"
  become: true
  apt_repository:
    repo: deb https://deb.nodesource.com/node_13.x bionic main
    update_cache: yes

- name: "Install nodejs"
  become: true
  apt:
    update_cache: yes
    name: nodejs
    state: present

- name: "install pm2 by npm"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

# Copy is incredible slow, so try sync
#- name: "copy files from CircleCI to Server"
#  copy:
#    src: /root/project/backend
#    dest: /home/ubuntu

- name: "sync files from CircleCI to Server"
  synchronize: 
    src: /root/project/backend
    dest: /home/ubuntu

- name: "install package dependencies"
  shell: |
    cd /home/ubuntu/backend    
    npm install 